/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Perdoruesi;
import BLL.Roli;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import DAL.MainException;
import DAL.PerdoruesiRepository;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import GUI.View.OrderHome;
/**
 *
 * @author taula
 */
public class LOGiN extends javax.swing.JFrame {

    /**
     * Creates new form LOGiN
     */
    Roli r=new Roli();
    public LOGiN() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        shtoRolin();
        
        
    }

    public JPasswordField getPassi() {
        return passi;
    }

    public void setPassi(JPasswordField passi) {
        this.passi = passi;
    }

    public JComboBox<String> getRolet() {
        return rolet;
    }

    public void setRolet(JComboBox<String> rolet) {
        
        this.rolet = rolet;
    }
    
    public void shtoRolin(){
       Roli r=new Roli();
       rolet.addItem(r.getEmertimi());
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.DARK_GRAY);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passi = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        Logini = new javax.swing.JButton();
        rolet = new javax.swing.JComboBox<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/View/IMG/logo2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("TYPOGRAPH PRO", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ready To Make An Order?");

        passi.setBackground(java.awt.Color.gray);
        passi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        passi.setForeground(new java.awt.Color(255, 255, 255));
        passi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("TYPOGRAPH PRO", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");

        Logini.setBackground(new java.awt.Color(83, 83, 83));
        Logini.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Logini.setForeground(new java.awt.Color(255, 255, 255));
        Logini.setText("Log In");
        Logini.setBorder(null);
        Logini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginiActionPerformed(evt);
            }
        });
        Logini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginiKeyPressed(evt);
            }
        });

        rolet.setBackground(java.awt.Color.darkGray);
        rolet.setForeground(new java.awt.Color(255, 255, 255));
        rolet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Deliver", "Admin" }));
        rolet.setSelectedIndex(1);
        rolet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roletActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel1))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(Logini, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(rolet, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passi, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rolet, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(passi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Logini, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(rolet, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginiActionPerformed
 try {
            PerdoruesiRepository pr = new PerdoruesiRepository();
            Perdoruesi p = pr.loginByUsernameAndPassword(new String(passi.getPassword()));
            try{
                if(p.getRoliID().getId() == 2 && rolet.getSelectedItem()=="Deliver"){  
                     OrderHome h = new OrderHome();
                     h.setVisible(true);
                      h.getDeliveri().setText("Deliveri "+p.getId());
                      h.getEmriDeliveri().setText(p.getUsername());
                       LOGiN.this.dispose();
                    }
            }catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, "Ju nuk jeni Admin", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    if(p.getRoliID().getId()==1 && rolet.getSelectedItem()=="Admin") {
                        AdminFrame a= new AdminFrame();
                        a.setVisible(true);
                       LOGiN.this.dispose();
                    }


            
        } catch (MainException ex) {
            System.out.println(ex.toString());
            JOptionPane.showMessageDialog(null, "Please type your password !", "ERROR", JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(this, ex.getMessage());
        }

//        if (passi.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Please type your password", "Error", JOptionPane.ERROR_MESSAGE);
//        } else if (!passi.getText().equals("Taulant") && !passi.getText().equals("Adnan")&& !passi.getText().equals("Vesa")) {
//            JOptionPane.showMessageDialog(null, "Your password is incorrect", "Error", JOptionPane.ERROR_MESSAGE);
//        }
//        if (passi.getText().equals("Taulant")) {
//            if (rolet.getSelectedItem() == "Deliver") {
//                OrderHome h = new OrderHome();
//                h.setVisible(true);
//                LOGiN.this.dispose();
//            } else {
//                JOptionPane.showMessageDialog(null, "Ju nuk jeni Admin", "ERROR", JOptionPane.ERROR_MESSAGE);
//            }
//        }
////        }else if (passi.getText().isEmpty()) {
////            JOptionPane.showMessageDialog(null, "Please type your password", "Error", JOptionPane.ERROR_MESSAGE);
////        } else {
////            JOptionPane.showMessageDialog(null, "Your password is incorrect", "Error", JOptionPane.ERROR_MESSAGE);
////       }
//
//        if (passi.getText().equals("Adnan")) {
//            if (rolet.getSelectedItem() == "Deliver") {
//                OrderHome h = new OrderHome();
//                h.setVisible(true);
//                h.getDeliveri().setText("Deliveri 2");
//                h.getEmriDeliveri().setText("Adnan Kasumaj");
//                LOGiN.this.dispose();
//            } else {
//                JOptionPane.showMessageDialog(null, "Ju nuk jeni Admin", "ERROR", JOptionPane.ERROR_MESSAGE);
//            }
//        }
//         }else if (passi.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Please type your password", "Error", JOptionPane.ERROR_MESSAGE);
//        } else {
//            JOptionPane.showMessageDialog(null, "Your password is incorrect", "Error", JOptionPane.ERROR_MESSAGE);
//        } 
//            if (passi.getText().equals("Vesa")) {
//                if (rolet.getSelectedItem() == "Admin") {
//                    AdminFrame a = new AdminFrame();
//                    a.setVisible(true);
//                    LOGiN.this.dispose();
//                } else {
//                    JOptionPane.showMessageDialog(null, "Ju nuk jeni Deliver", "ERROR", JOptionPane.ERROR_MESSAGE);
//                }
//            }
//        
    }//GEN-LAST:event_LoginiActionPerformed

    private void LoginiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginiKeyPressed

    }//GEN-LAST:event_LoginiKeyPressed

    private void roletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roletActionPerformed
        
    }//GEN-LAST:event_roletActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Drakula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGiN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGiN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGiN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGiN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGiN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logini;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passi;
    private javax.swing.JComboBox<String> rolet;
    // End of variables declaration//GEN-END:variables
}
