/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Product;
import GUI.View.CustomerTable;
import GUI.View.EmployeeTable;
import GUI.View.InvoiceTable;
import GUI.View.MenuTable;
import GUI.View.OrderTable;
import GUI.View.ProductCategoryTable;
import GUI.View.ProductTable;
import GUI.View.LOGiN;
import GUI.View.PaneliPije;
import GUI.View.PaneliUshqime;
import java.awt.Color;
import java.awt.Graphics;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JLabel;



import java.sql.Connection;
import java.sql.DriverManager; 
import java.util.HashMap;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager; 
import net.sf.jasperreports.engine.JasperPrint; 
import net.sf.jasperreports.engine.JasperReport; 
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author taula
 */
public class OrderHome extends javax.swing.JFrame {
    
    LOGiN log=new LOGiN();

    /**
     * Creates new form OrderHome
     */
    public OrderHome() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    public JDesktopPane getDpaneliUshqime() {
        return DpaneliUshqime;
    }

    
    
    public JLabel getDeliveri() {
        return Deliveri;
    }

    public void setDeliveri(JLabel Deliveri) {
        this.Deliveri = Deliveri;
    }

    public JLabel getEmriDeliveri() {
        return EmriDeliveri;
    }

    public void setEmriDeliveri(JLabel EmriDeliveri) {
        this.EmriDeliveri = EmriDeliveri;
    }
    
    
//    public void changeName(){
//        if(log.getPassi().equals("Taulant")){
//           Deliveri.setText("Deliveri 1");
//           EmriDeliveri.setText("Taulant Baba");
//        }else if(log.getPassi().equals("Adnan")){
//           Deliveri.setText("Deliveri 2");
//           EmriDeliveri.setText("Adnan Muti");
//        }
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        DpaneliUshqime = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.GRAY);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jLabel2 = new javax.swing.JLabel();
        DPaneliMenu = new javax.swing.JDesktopPane(){
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.setColor(Color.DARK_GRAY);
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Deliveri = new javax.swing.JLabel();
        EmriDeliveri = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logoutBtn = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        listButton = new javax.swing.JMenu();
        customerButton = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DpaneliUshqime.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Make Order");

        javax.swing.GroupLayout DpaneliUshqimeLayout = new javax.swing.GroupLayout(DpaneliUshqime);
        DpaneliUshqime.setLayout(DpaneliUshqimeLayout);
        DpaneliUshqimeLayout.setHorizontalGroup(
            DpaneliUshqimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DpaneliUshqimeLayout.createSequentialGroup()
                .addContainerGap(301, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(180, 180, 180))
        );
        DpaneliUshqimeLayout.setVerticalGroup(
            DpaneliUshqimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DpaneliUshqimeLayout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(328, 328, 328))
        );
        DpaneliUshqime.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        DPaneliMenu.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/View/logo2.png")));
        jLabel1.setText("jLabel1");

        jButton1.setBackground(new java.awt.Color(94, 94, 94));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Food");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(94, 94, 94));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Drinks");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(94, 94, 94));
        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sales Balance");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Deliveri.setFont(new java.awt.Font("TYPOGRAPH PRO", 0, 18)); // NOI18N
        Deliveri.setForeground(new java.awt.Color(255, 255, 255));
        Deliveri.setText("Delivery 1");

        EmriDeliveri.setFont(new java.awt.Font("TYPOGRAPH PRO", 0, 24)); // NOI18N
        EmriDeliveri.setForeground(new java.awt.Color(255, 255, 255));
        EmriDeliveri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmriDeliveri.setText("Taulant Fazliu");

        javax.swing.GroupLayout DPaneliMenuLayout = new javax.swing.GroupLayout(DPaneliMenu);
        DPaneliMenu.setLayout(DPaneliMenuLayout);
        DPaneliMenuLayout.setHorizontalGroup(
            DPaneliMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPaneliMenuLayout.createSequentialGroup()
                .addGroup(DPaneliMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DPaneliMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DPaneliMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(DPaneliMenuLayout.createSequentialGroup()
                .addGroup(DPaneliMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DPaneliMenuLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Deliveri))
                    .addGroup(DPaneliMenuLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(EmriDeliveri)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DPaneliMenuLayout.setVerticalGroup(
            DPaneliMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DPaneliMenuLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(Deliveri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmriDeliveri)
                .addGap(18, 18, 18))
        );
        DPaneliMenu.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DPaneliMenu.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DPaneliMenu.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DPaneliMenu.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DPaneliMenu.setLayer(Deliveri, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DPaneliMenu.setLayer(EmriDeliveri, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu1.setText("File");

        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jMenu1.add(logoutBtn);

        jMenuItem9.setText("Run Report");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        listButton.setText("List");

        customerButton.setText("Customers");
        customerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerButtonActionPerformed(evt);
            }
        });
        listButton.add(customerButton);

        jMenuItem2.setText("Employees");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        listButton.add(jMenuItem2);

        jMenuItem3.setText("Invoices");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        listButton.add(jMenuItem3);

        jMenuItem4.setText("Menu");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        listButton.add(jMenuItem4);

        jMenuItem5.setText("Orders");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        listButton.add(jMenuItem5);

        jMenuItem7.setText("Products");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        listButton.add(jMenuItem7);

        jMenuItem8.setText("Prod.Categorys");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        listButton.add(jMenuItem8);

        jMenuBar1.add(listButton);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DPaneliMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DpaneliUshqime))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DpaneliUshqime)
            .addComponent(DPaneliMenu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PaneliUshqime pu = new PaneliUshqime();
        DpaneliUshqime.add(pu);
        pu.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void customerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerButtonActionPerformed
        CustomerTable ct = new CustomerTable();
        DpaneliUshqime.add(ct);
        ct.show();
       ct.getjButton2().setVisible(false);
    }//GEN-LAST:event_customerButtonActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        EmployeeTable et = new EmployeeTable();
        DpaneliUshqime.add(et);
        et.show();
        et.getjButton2().setVisible(false);
        et.getSavebtn().setVisible(false);
        et.getCancel().setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        MenuTable mt = new MenuTable();
        DpaneliUshqime.add(mt);
        mt.show();
        mt.getjButton2().setVisible(false);
        mt.getSavebtn().setVisible(false);
        mt.getCancel().setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        InvoiceTable it = new InvoiceTable();
        DpaneliUshqime.add(it);
        it.show();
        it.getjButton2().setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        OrderTable ot = new OrderTable();
        DpaneliUshqime.add(ot);
        ot.show();
        ot.getjButton2().setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ProductCategoryTable pct = new ProductCategoryTable();
        DpaneliUshqime.add(pct);
        pct.show();
        pct.getjButton2().setVisible(false);
        pct.getSavebtn().setVisible(false);
        pct.getCancel().setVisible(false);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ProductTable pt = new ProductTable();
        DpaneliUshqime.add(pt);
        pt.show();
        pt.getjButton2().setVisible(false);
        pt.getSavebtn().setVisible(false);
        pt.getCancel().setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PaneliPije pi = new PaneliPije();
        DpaneliUshqime.add(pi);
        pi.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int pergjigjja=JOptionPane.showConfirmDialog(null, "Are you sure? ", "  Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);  
        if (pergjigjja == JOptionPane.YES_OPTION) {

                OrderHome.this.dispose();
                LOGiN l=new LOGiN();
                l.setVisible(true);
                
            }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try{  
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            InputStream in = new FileInputStream(new File("C:\\Users\\Adnan\\Documents\\NetBeansProjects\\Order-Delivery-System\\src\\Raportet\\Invoicee.jrxml"));
            JasperDesign jd = JRXmlLoader.load(in);
            String sql = "select * from Invoice";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            HashMap para = new HashMap();
            //Connection con = null;
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=OrderSystem", "Adnan" , "adnan123");
            JasperPrint j = JasperFillManager.fillReport(jr, para, con);
            JasperViewer.viewReport(j, false);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        InvoiceTable i = new InvoiceTable();
        DpaneliUshqime.add(i);
        i.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DPaneliMenu;
    private javax.swing.JLabel Deliveri;
    private javax.swing.JDesktopPane DpaneliUshqime;
    private javax.swing.JLabel EmriDeliveri;
    private javax.swing.JMenuItem customerButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu listButton;
    private javax.swing.JMenuItem logoutBtn;
    // End of variables declaration//GEN-END:variables
}
